name: Make a Stable Release

jobs:
  job1:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Cache Dependency
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Test Code
        run: |
          just test

      - name: Build Code
        run: |
          just Stable true

      - name: Package Source Code
        run: |
          zip -r Build/Release/HermesKit_source.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "target/*" \
            -x "Build/*" \
            -x "Lib/*" \
            -x "Include/*"

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Build/Release/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
